
// EECS 348 Assignment 1
// Program that gives a user 3 attempts to guess a secret number. Program checks if input is valid, and tells user if guess is too high or too low.
// Inputs: none
// Outputs: none
// Source: Generated by Gemini
// Author: Madelyn Armitage
// Creation Date: 09/04/2026
// Revision Date: 09/06/2026: 
// Revisions: added comments, improved edge cases to test for typing and value
// No collaborators



#include <stdio.h> //code to import standard in/out 


int main() { //opens up main for program to run
    int secret = 7; //creates integer variable "secret" to refer to secret number user attempts to guess
    int guess; //creates integer variable used later to store user's guess
    int max_attempts = 3; //creates integar variable to store the max number of guesses the user gets
    int won = 0; //integar variable used to indicate if the user won or lost. equals 0 if lost and 1 if won.

    printf("Guess a number between 1 and 10.\n"); //Prints line to prompt user to guess a number between 1 and 10

    for (int attempt = 1; attempt <= max_attempts; attempt++) { //a for loop that iterates through the following block of code 3 times (or whatever max_attempts is set equal to)
        printf("Attempt %d/%d. Enter your guess: ", attempt, max_attempts); //tells the user what attempt they are on and prompts a new guess

        //The following while loop runs repeatedly until the user provides good input. If the user gives a num lower than 1 or higher than 10, or a string, the program prompts them to enter valid input.
        while (1) { //opens while loop that runs until manually broken

        if (scanf("%d", &guess) != 1) { //checks that the user input is an integar type
            printf("Invalid input. Enter a number between 1 and 10: "); //if the user input is not an integar type, the user is prompted it give input again

            while (getchar() != '\n') { //clears out values from the input so the user can give new input
            }//closes while loop where characters were cleared

            continue;//starts the loop again because the user input was bad
        }//closes if loop that checked user input type

        if (guess < 1 || guess > 10) { //if statement to check if user guess was within 1 and 10, if not following code is run
            printf("Invalid input. Enter a number between 1 and 10: ");//prompts the user to guess again, because their input was bad
            continue;//starts the loop over when the user gives input again
        }//closes if statement checking user value was between 1 and 10

        break;//breaks loop if user input was an integar and between 1 and 10
        }//closes while loop that checks user input validity

        //the following if, else if, else block checks the user input against the secret number and then either continues the program or tells the user they win
        if (guess == secret) {//checks if the user guess was the secret number by comparing values
            printf("Correct! You win!\n"); //prints "correct" if the useer guessed the secret value
            won = 1; //If the user got the correct answer, integar variable becomes 1
            break; // Stops the loop immediately on a correct guess
        } else if (guess < secret) {//if user guess was below the secret number, prints "too low!"
            printf("Too low!"); //Prints "Too low" if user guess was too low
        } else { //runs following code if user guess was too high
            printf("Too high!"); //prints too high if user guess was too high
        }//closes else statement of the if, else if, else block

        //the following code allows the user to try again if they have more guesses left and did not guess the number
        if (attempt < max_attempts) {   // checks if users attempt number is less than the max_attempts they get
            printf(" Try again.\n"); //prints try again if the user gets another guess
            }//closes if statement checking max attempts and attempts
        else {//allows following code to run if user is out of attempts
            printf("\n"); //prints a new line if user does not have any attempts yet
            }//closes else statement of attempts if/else statement
        }//closes if else statement


    // Print final lose message if the user didn't win
    if (!won) {//checks won variable to see if user won. allows following code if user did not win
        printf("Out of attempts! The secret number was %d. You lose.\n", secret);//prints losing message if user did not sucessfully guess the number
    }//closes if statement

    return 0;//returns 0 to close out main
}//closes main