
// EECS 348 Assignment 1
// Program that gives a user 3 attempts to guess a secret number. Tells user if guess is too high or too low.
// Inputs: none
// Outputs: none
// Source: Generated by ChatGPT
// Author: Madelyn Armitage
// Creation Date: 09/04/2026
// No collaborators
#include <stdio.h>

int main() {
    int secretNumber = 7;
    int guess;
    int attempt = 1;

    printf("Guess a number between 1 and 10.\n");

    while (attempt <= 3) {
        printf("Attempt %d/3. Enter your guess: ", attempt);
        scanf("%d", &guess);

        if (guess == secretNumber) {
            printf("Correct! You win!\n");
            break;
        }
        else if (guess < secretNumber) {
            printf("Too low! Try again.\n");
        }
        else {
            printf("Too high! Try again.\n");
        }

        attempt++;
        
    if (guess != secretNumber) {
        printf("You lose! The secret number was %d.\n", secretNumber);
    }

    return 0;
    } 
} //bracket ends main (was missing from ChatGPT code. I had to add it for compiling.)